import Head from 'next/head'
import { Inter } from 'next/font/google'
import { trpcClient } from '@/utils/trpc'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const greeting = trpcClient.hello.useQuery({ text: 'Arjun' })
  if(!greeting.data) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className = {inter.className}>
          Hello {greeting.data.greeting}
        </div>
      </main>
    </>
  )
}
